[build]
# No default target set here (specify per-project or via `--target`)

# Use rust-lld for all bare-metal targets (ARM, RISC-V, etc.)
[target.'cfg(all(target_os = "none", not(target_arch = "avr")))']
linker = "rust-lld"
rustflags = [
    "-C", "link-arg=-Tlink.x",  # Default linker script (override per-project)
]

# Special case for AVR (does not use rust-lld)
[target.avr-unknown-gnu-atmega328]
linker = "avr-gcc"  # AVR requires GCC linker

# Example for RISC-V
[target.riscv32imc-unknown-none-elf]
linker = "rust-lld"
rustflags = [
    "-C", "link-arg=-Tlink.x",
    "-C", "linker-plugin-lto",
]

# Example for 

[target.xtensa-esp32-none-elf]
linker = "ld"  # ESP32 uses its own custom ld
rustflags = [
    "-C", "link-arg=-Tlink.x",
]