[build]
target = "thumbv7em-none-eabihf"

# ARM target settings
[target.thumbv7em-none-eabihf]
runner = "probe-rs run --chip STM32F303VCTx" 
# runner = "arm-none-eabi-gdb -q -x ../openocd.gdb"
linker = "rust-lld"
rustflags = [
    "-C", "link-arg=-Tlink.x",
    "-C", "linker-flavor=ld.lld",
]

# Reset flags for host builds
[target.'cfg(windows)']
rustflags = []

[profile.dev]
opt-level = 0
debug = 2